basic_if = "prefix%{ if var.enabled }yes%{ endif }suffix"
if_else = "%{ if var.enabled }yes%{ else }no%{ endif }"
strip_markers = "%{~ if var.enabled ~}yes%{~ endif ~}"
strip_partial = "%{~ if var.enabled }yes%{ endif ~}"
basic_for = "%{ for item in var.list }${item}%{ endfor }"
for_key_value = "%{ for k, v in var.map }${k}=${v}%{ endfor }"
issue_247 = "kms%{ if var.id != \"primary\" }-${var.id}%{ endif }"
mixed = "${var.prefix}%{ if var.suffix }-${var.suffix}%{ endif }"
nested_if = "%{ if a }%{ if b }both%{ endif }%{ endif }"
escaped_directive = "use %%{literal} not directives"
for_with_interp = "%{ for x in var.items }item=${x}, %{ endfor }"
if_strip_else_strip = "%{~ if cond ~}a%{~ else ~}b%{~ endif ~}"
