# pylint: disable=missing-function-docstring,unused-argument


from lark import Transformer, Tree, Token
from lark.visitors import _Leaf_T, _Return_T

from hcl2.serialization import LarkRule, LarkToken


class RuleTransformer(Transformer):
    """Takes a syntax tree generated by the parser and
    transforms it to a tree of LarkRule instances
    """

    with_meta: bool

    # @classmethod
    # def set_processing_methods(cls):
    #
    #     for _class in LarkRule._classes:
    #
    #         m = lambda transformer, children: _class.process(transformer, children)
    #         print(_class)
    #         setattr(cls, _class.rule_name(), m)

    @staticmethod
    def is_type_keyword(value: str) -> bool:
        return value in {"bool", "number", "string"}

    def __init__(self, with_meta: bool = False):
        """
        :param with_meta: If set to true then adds `__start_line__` and `__end_line__`
        parameters to the output dict. Default to false.
        """
        self.with_meta = with_meta
        super().__init__()

    def transform(self, tree: Tree[_Leaf_T]) -> LarkRule:
        return super().transform(tree)

    def __default_token__(self, token: Token) -> LarkToken:
        return LarkToken(token.type, token.value)


for _class in LarkRule._classes:
    setattr(RuleTransformer, _class.rule_name(), _class.process)
