---
name: Dependencies Check
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - pyproject.toml
      - requirements.txt
      - scripts/check_deps.py

jobs:
  test:
    name: Check dependencies sync between pyproject.toml and requirements.txt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install dependencies
        run: python -m pip install --upgrade tomli
      - name: Run script
        run: python3 bin/check_deps.py
