name: build

on:
  push:
    branches:
      - master
jobs:

  bump-version:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@master
      - name: update docs and bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest tag: $latest_tag"
          new_tag=$(echo $latest_tag | awk -F. -v a="$1" -v b="$2" -v c="$3" '{printf("%d.%d.%d", $1+a, $2+b , $3+1)}')
          echo "new tag: $new_tag"

          ## update python version
          echo "__version__ = '$new_tag'" > 'hcl2/version.py'

          git commit --reuse-message=HEAD@{1} hcl2/version.py || echo "No changes to commit"
          git push origin
          git tag $new_tag
          git push origin $new_tag
  publish-package:
    needs: bump-version
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - name: create python package
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          git pull
          pipenv run pip install -r requirements.pip -e .
          pipenv run python hcl2/parser.py
          pipenv run python setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
      - name: sleep and wait for package to refresh
        run: |
          sleep 2m
